[package]
name = "blurz"
version = "0.1.7"
description = "Bluetooth lib for Rust using blueZ/dbus"
readme = "README.md"
authors = ["Attila Dusnoki <adusnoki@inf.u-szeged.hu>"]
repository = "https://github.com/szeged/blurz"
keywords = ["bluetooth", "bluez", "ble"]
license = "BSD-2-Clause"

[lib]
name = "blurz"
path = "src/lib.rs"

[dependencies]
dbus = "0.3.2"
rustc-serialize = "0.3"
