[package]
name = "blurz"
version = "0.2.3"
description = "Bluetooth lib for Rust using blueZ/dbus"
readme = "README.md"
authors = ["Attila Dusnoki <adusnoki@inf.u-szeged.hu>"]
repository = "https://github.com/szeged/blurz"
keywords = ["bluetooth", "bluez", "ble"]
license = "BSD-2-Clause"

[lib]
name = "blurz"
path = "src/lib.rs"

[dependencies]
dbus = "0.6"
hex = "0.2.0"
